os:
  - linux

sudo: required
dist: trusty
language: cpp
script: scons

compiler:
  - gcc
  - clang
addons:
   apt:
    # List of whitelisted in travis packages for ubuntu-trusty can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - cmake
    - scons
    - gcc-7
    - g++-7
    - clang-5.0
install:

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

    - "[ $CC = gcc ] && export CC=gcc-7 || true"
    - "[ $CXX = g++ ] && export CXX=g++-7 || true"
    - echo ${CC}
    - ${CC} --version
    - echo ${CXX}
    - ${CXX} --version

branches:
  only:
    - master

notifications:
email: true

before_script:
   - mkdir -p build && cd build
   - cmake .. -DCMAKE_BUILD_TYPE=Debug
   - cmake --build .
   - cd ..

script:
   - cd build 

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"