os:
  - linux

sudo: required
dist: trusty
language: cpp
script: scons

compiler:
  - gcc
  - clang
addons:
   apt:
    # List of whitelisted in travis packages for ubuntu-trusty can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - cmake
    - scons
    - gcc-7
    - g++-7
    - clang-5.0
install:
- "[ $CC = gcc ] && export CC=gcc-7 || true"
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- echo ${CC}
- ${CC} --version
- echo ${CXX}
- ${CXX} --version

branches:
  only:
    - master

notifications:
email: true

before_script:
   - mkdir -p build && cd build
   - cmake .. -DCMAKE_BUILD_TYPE=Debug
   - cmake --build .
   - cd ..

script:
   - cd build 

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"