os:
  - linux

sudo: required
dist: trusty
language: cpp
script: scons

compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-6
    - g++-6
    - clang-3.8
install:
- "[ $CXX = gcc ] && export CXX=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

branches:
  only:
    - master

notifications:
email: devteam@phonemetra.com

script:
  - make

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"